Unify tests (sort of)
tests/Main.hs simply runs the 'main' functions exported by Properties.hs
and Commands.hs.
This makes it simple to run all tests, and allows us to generate _full_
code coverage reports thus:

     $ cd tests
     $ ghc -i.. -fhpc --make Main.hs
     $ Main
     $ hpc markup Main

darcs-hash:20080305201206-928c4-7835493b938e53143f38989394be601f8220502a.gz

diff --git a/tests/run-tests b/tests/run-tests
--- a/tests/run-tests
+++ b/tests/run-tests
@@ -3,11 +3,11 @@
 # Run tests and signal error on failure.
 # Saves output in 'test.log', unless no failures are detected.
 
-runhaskell -iNetwork tests/Properties.hs \
-    | tee test.log && if grep Falsifiable test.log >/dev/null ; then exit 1 ;
-else rm -f test.log ; fi
-
-runhaskell -iNetwork tests/Commands.hs \
-    | tee test.log && \
-    if grep "\*\*\* FAILURE \*\*\*" test.log >/dev/null ; then \
-        exit 1 ; else rm -f test.log ; fi
+runhaskell -itests tests/Main.hs | tee test.log
+if $(grep Falsifiable test.log >/dev/null) \
+    || $(grep "\*\*\* FAILURE \*\*\*" test.log >/dev/null) ; then
+    #echo "Failure detected!"
+    exit 1
+else
+    rm test.log
+fi
